# Deep learning configuration file ------------------------------------------------
# This config is to use massachusetts_buildings image out of the box WITH ONLY MANDATORY PARAMETERS.
# For that, unzip the file data/massachusetts_buildings.zip before running data_to_tiles.py or other command.
# Five sections :
#   1) Global parameters; those are re-used amongst the next three operations (sampling, training and inference)
#   2) Sampling parameters
#   3) Training parameters
#   4) Inference parameters

# Global parameters
global:
  samples_size: 512
  num_classes: 1
  number_of_bands: 3
  model_name: unet  # See models/README.md for all the available models.

# Sample parameters; used in data_to_tiles.py -------------------
sample:
  prep_csv_file: .data/images_to_samples_ci_csv.csv  # /path/to/csv/images.csv

# Training parameters; used in train_segmentation.py ----------------------
training:
  batch_size: 2
  num_epochs: 1

# Inference parameters; used in inference.py --------
inference:
  img_dir_or_csv_file: # /path/to/csv/containing/images/list.csv
  state_dict_path: # optional: /path/to/model/weights/for/inference/checkpoint.pth.tar