# @package _global_
dataset:
  # dataset-wide
  name:
  input_dim: 256
  overlap:
  use_stratification: False
  train_val_percent: {'trn':0.7, 'val':0.3, 'tst':0}
  raw_data_csv: ${general.raw_data_csv}
  raw_data_dir: ${general.raw_data_dir}

  # imagery
  modalities: [red, green, blue]

  # ground truth
  attribute_field: properties/class
  attribute_values: [1]
  min_annot_perc:
  class_name: # will follow in the next version
  classes_dict:
    WAER:
    FORE:
    ROAI:
    BUIL: 1
  class_weights:
  ignore_index: -1

  # outputs
  sample_data_dir: ${general.sample_data_dir}

