# @package _global_
dataset:
  # dataset-wide
  name:
  input_dim: 256
  overlap:
  use_stratification: False
  train_val_percent: {'trn':0.7, 'val':0.3, 'tst':0}
  raw_data_csv: ${general.raw_data_csv}
  raw_data_dir: data  #${general.raw_data_dir}

  # imagery
  bands: [red, green, blue, nir]

  # ground truth
  attribute_field: properties/class
  attribute_values: [1]  # class(es) that you want to process, ex [1] only process class 1, [1, 2] will process two classes 
  min_annot_perc:
  class_name: # will follow in the next version
  classes_dict:
    FORE: 1
    WAER: 2
    ROAI: 3
    BUIL: 4
  class_weights:
  ignore_index: -1

  # outputs
  sample_data_dir: ${general.sample_data_dir}

