# @package _global_
inference:
  img_dir_or_csv_file: ${general.raw_data_csv}
  state_dict_path: ${general.save_weights_dir}/checkpoint.pth.tar
  chunk_size: 256
  # Visualization parameters
  smooth_prediction: True
  overlap: 2
  ras2vec: False